extension_dir = "C:\Program Files\php\ext"
extension=pdo_mysql
extension=pdo_sqlite
extension=fileinfo
extension=mbstring
upload_max_filesize = 20M
post_max_size = 25M
display_errors = On
display_startup_errors = On
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT
